### ISSUE TITLE
-202 (202) wrong password at umail.SMTP()

### ISSUE THREAD

**Issue by davefes** [shawwwn/uMail#10]
Been trying to track down the odd error when sending a daily log.

`
try:
    smtp = umail.SMTP('smtp.gmail.com', 465, ssl=True)
except Exception as error:
    try:
        with open('errors.txt', 'a') as outfile:
            outfile.write(str(error) + '\n')
    except OSError:
        print('oops')
`

What I don't understand and Google doesn't seem to have an answer is why do I see the error on this call and not the next call:
`
smtp.login('davef@gmail.com', 'myPassword')
`
where I don't even have any logging.

Sorry can't figure out how to sort the code block.

Thanks

**Comment by shawwwn** [comment]
https://github.com/shawwwn/uMail/issues/8
It seems like you encounter the same error as before, are you sure your DNS resolves correctly?

**Comment by davefes** [comment]
Since changing to 8.8.8.8 the error rate dropped, say by a factor of 10.  I  mistakenly thought I might be seeing another problem. Maybe, I should have re-opened #8.  I will Google for a method to check that DNS resolves correctly before trying to send the email.  Thanks, Dave

**Comment by davefes** [comment]
Setup a simple script which repetitively called getaddrinfo().  On the ESP32 with esp32-idf4-20210202-v1.14 random -202 errors are generated.  As I think this leaves uMail "out of the loop" I am closing the issue.
