### ISSUE TITLE
Multiple Emails

### ISSUE THREAD

**Issue by lankylad9** [shawwwn/uMail#16]
Don't seem to be able to send multiple emails?

**Comment by shawwwn** [comment]
To send to multiple recipients, simply pass in an array instead of one string

`
smtp.to(['a@gmail.com', 'b@gmail.com'])
`

**Comment by lankylad9** [comment]
Sorry, I meant I cant send more than one email. The second email doesnt seem to go?

**Comment by lankylad9** [comment]
Sorry again, I didn't realise that I needed to give my email credentials each time.
