### ISSUE TITLE
Can't send mail using Outlook (OS Error)

### ISSUE THREAD

**Issue by Vultik** [shawwwn/uMail#17]
I have not succeed to send mail using outlook. It works great with Gmail though.
I'm using MicroPython v1.19.1 on ESP32.
Here my code :
```python
import umail

SMTP_PORT = 587
SMTP_HOST = "smtp.office365.com"
SMTP_USERNAME = "xxxx@outlook.com"
SMTP_PASSWORD = "xxx"

WIFI_AP_SSID = "xxx-ap"
WIFI_AP_PASSWORD = "xxx"

def do_connect():
    import network
    wlan = network.WLAN(network.STA_IF)
    wlan.active(True)
    if not wlan.isconnected():
        print('connecting to network...')
        wlan.connect(WIFI_AP_SSID, WIFI_AP_PASSWORD)
        while not wlan.isconnected():
            pass
    print('network config:', wlan.ifconfig())


if __name__ == "__main__":
    do_connect()
    smtp = umail.SMTP(host=SMTP_HOST, port=SMTP_PORT, ssl=True, username=SMTP_USERNAME, password=SMTP_PASSWORD)
    smtp.to('noreply@example.com')
    smtp.send("Hello ?")
    smtp.quit()
```

If i'm not using SSL, there is no error, but i don't receive the mail (maybe it's a different SMTP port)

<img width="620" alt="umail_error" src="https://user-images.githubusercontent.com/55872753/201730587-a2c74569-ba76-4bdd-a923-f197087df8ba.PNG">

**Comment by shawwwn** [comment]
Looks like Outlook.com only supports [STARTSSL protocol](https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-8361e398-8af4-4e97-b147-6c6c4ac95353).
STARTSSL protocol usually means first connect in plaintext; upon server's request, wrap the connection with SSL encryption.
So you should not need to specify `ssl=True` in your code, SSL session will start (upon server's request) regardless of your initial setting.

**Comment by Vultik** [comment]
Ok, 
I thought that it doesn't work without SSL, but the mail was in the spam ...
I think it will be great to add some features like :
- add mail object
- add encoding support : it doesn't work with utf-8 char
- add html support
- add attachment support

Thanks for this minimal great uPython lib !
