### ISSUE TITLE
Setting subject: in email

### ISSUE THREAD

**Issue by mikerr** [shawwwn/uMail#23]
Using smtp.send was coming up with a blank subject field

Perhaps obvious, but I found to add it you add ` Subject: `  followed by two return characters before the content of the email,

i.e.

`smtp.send("Subject:  status update  \n\n" + content)`

Hope that helps !

**Comment by shawwwn** [comment]
Thanks.

Also for embedding images in email, take a look at MIME extension (https://en.wikipedia.org/wiki/MIME#MIME_header_fields).
