### ISSUE TITLE
Suggest add an example where the parameters are variables

### ISSUE THREAD

**Issue by ExperiMentor** [shawwwn/uMail#27]
When the message parameters are variables rather than constants, it is necessary to include an explicit "\n" at the end of each line. One or more examples showing how to do this would be useful. I am successful with:

`smtp = umail.SMTP(host='smtp.gmail.com', port=465, ssl=True, username=mailFrom, password=mailPass)

def send_email(destination, subject, message):
    global smtp, mailFrom
    smtp.to(destination)
    smtp.write("To: " + destination + "\n")
    smtp.write("From: " + mailFrom + "\n")
    smtp.write("Subject: " + subject + "\n")
    smtp.write(message + "\n")
    smtp.send()
    smtp.quit()

**Comment by shawwwn** [comment]
Thanks for the suggestion. Newline characters are already included in one of the examples.
https://github.com/shawwwn/uMail/blob/master/examples/example_ssl.py
