### ISSUE TITLE
multiple recipients not work, and smtp.quit() spits errors

### ISSUE THREAD

**Issue by kenjican** [shawwwn/uMail#31]
About multiple recipients : At line 83 addrs = [addrs] should be revised to addrs =  addrs.split(',') , And multiple recipients in  string split by comma.
  smtp.quit() generates error: ValueError: invalid syntax for integer with base 10 . I doesn't  
 affect sending the mail. but a little annoying. Could somebody fix this error?

**Comment by shawwwn** [comment]
Hi.
Thank you for the feedback!

> About multiple recipients ...

The intention behind `addrs` argument is: if you supply only one string, then the program would assume you want to send only to one recipient, so the string will be treated as an email address; but if you want to send to multiple recipients, you would supply a list of string(eg, `['a@gmail.com', 'b@gmail.com', 'c@gmail.com']`).
I think this is more intuitive.

> smtp.quit() generates error: ValueError: invalid syntax for integer with base 10

This is weird.
Can you find out the content of variable `code` (in byte format) after `smtp.quit()` has been called?
https://github.com/shawwwn/uMail/blob/c95531fcf1167bd9eda3dde49a9cff8127865f8c/umail.py#L25

**Comment by kenjican** [comment]
Hi 

Thanks for the quick reply.   

At line 24 , I add this: print(code) ,and get below:


b'250'
b'250'
b'334'
b'235'
b'250'
b'250'
b'354'
b'\x00\x00\x00'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "email.py", line 14, in <module>
  File "umail.py", line 110, in quit
  File "umail.py", line 26, in cmd
ValueError: invalid syntax for integer with base 10

**Comment by shawwwn** [comment]
Yeah, that's what I thought. Server closes the connection as soon as it receives the "QUIT" command without sending a proper reply hence the null characters client received.
I probably won't be fixing this because it is not standard behaviors expected from the server side.
For a quick fix, feel free to wrap the `.quit()` function with try..except clause.

**Comment by kenjican** [comment]
Thanks, it works. ;)
