### ISSUE TITLE
micropython error upycraft ide

### ISSUE THREAD

**Issue by mikronauts** [shawwwn/uMail#4]
Error when trying to send an email:

download ok
exec(open('um.py').read(),globals())
Traceback (most recent IndexError: list index out of range

Traced it to latest umail.py (downloaded today) line 30

**Comment by shawwwn** [comment]
Are you running umail on Windows?

**Comment by mikronauts** [comment]
No trying to run it on an esp32 devkitc

**Comment by shawwwn** [comment]
Does your esp32 have internet access when running umail?

**Comment by mikronauts** [comment]
My apologies, you are right ... I had connecting to my network commented out.

Great library, great support!
