### ISSUE TITLE
error in umail

### ISSUE THREAD

**Issue by ggrobi** [shawwwn/uMail#5]
Hi, using the SSL example and allowing Gmail to lower security level I had success.
thanks for supplying the code. 
cheers
Gary

Hi, thanks very much for you umail.py

using example 
#
# An bare minimium example for sending a email
# without SSL connection
# 

get this error when I run the example code in REPL

exec(open('test1gmail.py').read(),globals())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 7, in <module>
  File "umail.py", line 30, in __init__
IndexError: list index out of range

**Comment by shawwwn** [comment]
I think the `usocket.getaddrinfo()` has failed.
You may need to check if your internet connection to smtp.gmail.com:587 is open.

**Comment by shawwwn** [comment]
I'm surprised that it didn't raise an error as indicated in mpy's manual.
http://docs.micropython.org/en/v1.9.3/pyboard/library/usocket.html#usocket.getaddrinfo

**Comment by shawwwn** [comment]
closed b/c no further discussion.
