### ISSUE TITLE
Trying to get this work but get this handshake error - no clue what to do

### ISSUE THREAD

**Issue by johncblacker** [shawwwn/uMail#7]
I'm getting the following error and don't know how to fix:
*********************************
mbedtls_ssl_handshake error: -71

Traceback (most recent call last):

  File "V:\xfer-to-ubuntu\lemariva\timelapse\uMail\uMail-master\uMail-master\examples\example_basic.py", line 18, in <module>

  File "/lib/umail.py", line 46, in __init__

OSError: [Errno 5] EIO
******************************************** end of error output *****************************
Do you have any clues that will help me?

**Comment by shawwwn** [comment]
This depends on the underlying implementation of the ussl module in micropython.
It's beyond the scope of this tool. I'm afraid you need to reach micropython developers.

**Comment by johncblacker** [comment]
ok, thanks. I just thought you would be able to help. What is the minimum uPy vers for your code to work? Are you aware of any esp32  uPy distributions it has been run on?

**Comment by shawwwn** [comment]
A quick search(https://github.com/micropython/micropython/issues/5543) reveals that it was mostly likely due a regression in the esp32 sdk(the thing micropython builds on).
Maybe trying it out on some older versions of micropython?

**Comment by johncblacker** [comment]
thanks.
